from web.template import CompiledTemplate, ForLoop, TemplateResult


# coding: utf-8
def layout_old():
    __lineoffset__ = -5
    loop = ForLoop()
    self = TemplateResult(); extend_ = self.extend
    extend_([u'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n'])
    extend_([u'<html xmlns="http://www.w3.org/1999/xhtml">\n'])
    extend_([u'<head>\n'])
    extend_([u'    <title>ProfessionalIT - Sistemas, Sites, Aplica\xe7\xf5es Web e Mobile.</title>\n'])
    extend_([u'    <meta name="language" content="pt-br"/>\n'])
    extend_([u'    <meta http-equiv="content-type" content="text/html; charset=UTF-8">\n'])
    extend_([u'    <meta name="copyright" content="Copyright (c) 2011 ProfessionalIT. This site\'s design and html code is licensed under the terms of the GPLv3 or (at your option) any later version.">\n'])
    extend_([u'    <meta name="organization name" content="ProfessionalIT - Sistemas, Sites, Aplica\xe7\xf5es Web e Mobile." />\n'])
    extend_([u'    <meta name="author" content="professionalit.com.br - Sistemas, Sites, Aplica\xe7\xf5es Web e Mobile."/>\n'])
    extend_([u'    <meta name="Description" content="Empresa de desenvolvimento de sistemas, sites, aplica\xe7\xf5es web e sistemas mobile." lang="pt-BR">\n'])
    extend_([u'    <meta name="Keywords" content="Sistema, Sites, WebSite, Mobile, Aplica\xe7\xf5es, Software, Desenvolvimento, Tecnologia, Open-Source, Python, Linux, Django, Web2Py, GAE, Google Apps" lang="pt-BR">\n'])
    extend_([u'    <meta name="rating" content="Sistemas, Sites, Aplica\xe7\xf5es Web, Aplica\xe7\xf5es Mobile">\n'])
    extend_([u'    <meta name="DC.title" content="professionalit.com.br">\n'])
    extend_([u'    <meta name="robots" content="ALL">\n'])
    extend_([u'    <meta name="googlebot" content="all" />\n'])
    extend_([u'    <meta name="generator" content="Geany 0.19" />\n'])
    extend_([u'    <meta name="classification" content="Internet" />\n'])
    extend_([u'    <meta name="distribution" content="Global" />\n'])
    extend_([u'    <meta name="revisit-after" content="2 weeks" />\n'])
    extend_([u"    <link rel='index' title='ProfessionalIT - Sistemas, Sites, Aplica\xe7\xf5es Web e Mobile.' href='http://www.professionalit.com.br' ></link>\n"])
    extend_([u'    <link rel="canonical" href="http://www.professionalit.com.br" ></link>\n'])
    extend_([u'    <link href="/static/css/style.css" rel="stylesheet" type="text/css"/>\n'])
    extend_([u'</head>\n'])
    extend_([u'<body>\n'])
    extend_([u'    <div id="main_panel">\n'])
    extend_([u'        <img src="/static/images/logotipo.png" alt="logotipo da ProfessionalIT." border="0"/>\n'])
    extend_([u'        <h1>Uma empresa de Solu\xe7\xf5es em Tecnologia.</h1>\n'])
    extend_([u'    </div>\n'])
    extend_([u'    <div id="container">\n'])
    extend_([u'        <h3>No que somos especialistas e com certeza podemos te ajudar:</h3>\n'])
    extend_([u'        <ul id="nav">\n'])
    extend_([u'            <li id="selected"><a href="#">Sistemas</a></li>\n'])
    extend_([u'            <li><a href="#">Websites</a></li>\n'])
    extend_([u'            <li><a href="#">Aplica\xe7\xf5es Web</a></li>\n'])
    extend_([u'            <li><a href="#">Aplica\xe7\xf5es Mobile</a></li>\n'])
    extend_([u'        </ul>\n'])
    extend_([u'    </div>\n'])
    extend_([u'    <div id="contact_panel" >\n'])
    extend_([u'         <p style="text-align:center;">Clientes, not\xedcias e acontecimentos em:</p>\n'])
    extend_([u'         <table>\n'])
    extend_([u'            <tr>\n'])
    extend_([u'                <td><a href="http://blog.professionalit.com.br" title="Blog da ProfessionalIT - Sistemas, Sites, Aplica\xe7\xf5es Web e Aplica\xe7\xf5es Mobile."><img src="/static/images/Blogger_72.png" alt="Logotipo do Blogger." title="Blog da ProfessionalIT - Sistemas, Sites, Aplica\xe7\xf5es Web e Aplica\xe7\xf5es Mobile."/></a></td>\n'])
    extend_([u'                <td><a href="http://www.twitter.com/professionalit" title="Twitter da ProfessionalIT - Sistemas, Sites, Aplica\xe7\xf5es Web e Aplica\xe7\xf5es Mobile."><img src="/static/images/Twitter_72.png" alt="Logotipo do Twitter." title="Twitter da ProfessionalIT - Sistemas, Sites, Aplica\xe7\xf5es Web e Aplica\xe7\xf5es Mobile." /></a></td>\n'])
    extend_([u'                <td><a href="http://pt-br.facebook.com/pages/ProfessionalIT-Sistemas-Sites-Aplica%C3%A7%C3%B5es-Web-e-Aplica%C3%A7%C3%B5es-Mobile/172556429456889" title="Facebook da ProfessionalIT - Sistemas, Sites, Aplica\xe7\xf5es Web e Aplica\xe7\xf5es Mobile."><img src="/static/images/Facebook_72.png" alt="Logotipo do Facebook." title="Facebook da ProfessionalIT - Sistemas, Sites, Aplica\xe7\xf5es Web e Aplica\xe7\xf5es Mobile."/></a></td>\n'])
    extend_([u'            </tr>\n'])
    extend_([u'            <tr>\n'])
    extend_([u'                <td><a href="http://blog.professionalit.com.br" title="Blog da ProfessionalIT - Sistemas, Sites, Aplica\xe7\xf5es Web e Aplica\xe7\xf5es Mobile.">Nosso Blog</a></td>\n'])
    extend_([u'                <td><a href="http://www.twitter.com/professionalit" title="Twitter da ProfessionalIT - Sistemas, Sites, Aplica\xe7\xf5es Web e Aplica\xe7\xf5es Mobile.">Nosso Twitter</a></td>\n'])
    extend_([u'                <td><a href="http://pt-br.facebook.com/pages/ProfessionalIT-Sistemas-Sites-Aplica%C3%A7%C3%B5es-Web-e-Aplica%C3%A7%C3%B5es-Mobile/172556429456889" title="Facebook da ProfessionalIT - Sistemas, Sites, Aplica\xe7\xf5es Web e Aplica\xe7\xf5es Mobile.">Nosso Facebook</a></td>\n'])
    extend_([u'            </tr>\n'])
    extend_([u'         </table>\n'])
    extend_([u'         Estamos \xe0 tua disposi\xe7\xe3o: <span>+55 51 9390.3511</span> | E-mail: comercial@professionalit.com.br\n'])
    extend_([u'    </div>\n'])
    extend_([u'    <div style="width: 50%; margin: 0px auto;">\n'])
    extend_([u'        <h4>Deixe seu recado que entraremos em contato:</h4>\n'])
    extend_([u'        <form action="" method="post"> \n'])
    extend_([u'            <table> \n'])
    extend_([u'                <tr><th><label for="nome">Nome:</label></th><td><input name="nome" title="Informe o seu nome." maxlenght="250" type="text" id="nome" size="60"/></td></tr> \n'])
    extend_([u'                <tr><th><label for="email">E-mail:</label></th><td><input name="email" title="Informe o seu E-mail." maxlenght="250" type="text" id="email" size="60"/></td></tr> \n'])
    extend_([u'                <tr><th><label for="telefone">Telefone:</label></th><td><input name="telefone" title="Informe o seu telefone." maxlenght="250" type="text" id="telefone" size="60"/></td></tr> \n'])
    extend_([u'                <tr><th><label for="mensagem_adicional">Mensagem:</label></th><td><textarea title="Inclua sua mensagem." rows="15" id="mensagem_adicional" name="mensagem_adicional" cols="47"></textarea></td></tr> \n'])
    extend_([u'                <tr><th><label for="Submit!"></label></th><td><button type="submit" id="Submit!" name="Submit!">Enviar</button></td></tr> \n'])
    extend_([u'            </table> \n'])
    extend_([u'        </form> \n'])
    extend_([u'    </div>\n'])
    extend_([u'    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js" type="text/javascript"></script>\n'])
    extend_([u'    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js"></script>\n'])
    extend_([u'    <script type="text/javascript" src="/static/javascript/jquery.spasticNav.js"></script>\n'])
    extend_([u'    <script type="text/javascript">\n'])
    extend_([u"        jQuery('#nav').spasticNav();\n"])
    extend_([u'    </script>\n'])
    extend_([u'</body>\n'])
    extend_([u'</html>\n'])

    return self

layout_old = CompiledTemplate(layout_old, 'templates/site/layout_old.html')
join_ = layout_old._join; escape_ = layout_old._escape

# coding: utf-8
def layout():
    __lineoffset__ = -5
    loop = ForLoop()
    self = TemplateResult(); extend_ = self.extend
    extend_([u'<!DOCTYPE html>\n'])
    extend_([u'<html lang="en">\n'])
    extend_([u'\n'])
    extend_([u'<head>\n'])
    extend_([u'\n'])
    extend_([u'    <meta charset="utf-8">\n'])
    extend_([u'    <meta http-equiv="X-UA-Compatible" content="IE=edge">\n'])
    extend_([u'    <meta name="viewport" content="width=device-width, initial-scale=1">\n'])
    extend_([u'    <meta name="copyright"\n'])
    extend_([u'          content="Copyright (c) Maxig\xeanios - Genialidade em Solu\xe7\xf5es Tecnol\xf3gicas. This site\'s design and html code is licensed under the terms of the GPLv3 or (at your option) any later version.">\n'])
    extend_([u'    <meta name="organization name"\n'])
    extend_([u'          content="Maxig\xeanios - Genialidade em Solu\xe7\xf5es Tecnol\xf3gicas.">\n'])
    extend_([u'    <meta name="description"\n'])
    extend_([u'          content="Maxig\xeanios - Genialidade em Solu\xe7\xf5es Tecnol\xf3gicas.">\n'])
    extend_([u'    <meta name="Keywords" content="Sistema, Sites, WebSite, Mobile, Aplica\xe7\xf5es Web, Aplica\xe7\xf5es Mobile, E-Commerce, Com\xe9rcio Eletr\xf4nico, Software, Desenvolvimento, Tecnologia, Open-Source, Desenvolviment de Sistemas, Desenvolvimento de Software" lang="pt-BR">\n'])
    extend_([u'    <meta name="rating" content="Sistema, Sites, WebSite, Mobile, Aplica\xe7\xf5es Web, Aplica\xe7\xf5es Mobile, E-Commerce, Com\xe9rcio Eletr\xf4nico, Software, Desenvolvimento, Tecnologia, Open-Source, Desenvolviment de Sistemas, Desenvolvimento de Software">\n'])
    extend_([u'    <meta name="DC.title" content="maxigenios.com.br">\n'])
    extend_([u'    <meta name="robots" content="ALL">\n'])
    extend_([u'    <meta name="googlebot" content="all">\n'])
    extend_([u'    <meta name="classification" content="Internet">\n'])
    extend_([u'    <meta name="distribution" content="Global">\n'])
    extend_([u'    <meta name="revisit-after" content="1 weeks">\n'])
    extend_([u'    <meta name="author" content="maxigenios.com.br - Maxig\xeanios - Genialidade em Solu\xe7\xf5es Tecnol\xf3gicas.">\n'])
    extend_([u'\n'])
    extend_([u'    <link rel="index"\n'])
    extend_([u'          title="Maxig\xeanios - Genialidade em Solu\xe7\xf5es Tecnol\xf3gicas."\n'])
    extend_([u'          href="http://www.maxigenios.com.br" ></link>\n'])
    extend_([u'\n'])
    extend_([u'    <title>Maxig\xeanios - Genialidade em Solu\xe7\xf5es Tecnol\xf3gicas.</title>\n'])
    extend_([u'\n'])
    extend_([u'    <!-- Bootstrap Core CSS -->\n'])
    extend_([u'    <link href="/static/css/bootstrap.min.css" rel="stylesheet">\n'])
    extend_([u'\n'])
    extend_([u'    <!-- Custom CSS -->\n'])
    extend_([u'    <link href="/static/css/landing-page.css" rel="stylesheet">\n'])
    extend_([u'\n'])
    extend_([u'    <!-- Custom Fonts -->\n'])
    extend_([u'    \n'])
    extend_([u'    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">\n'])
    extend_([u'\n'])
    extend_([u'    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n'])
    extend_([u"    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n"])
    extend_([u'    <!--[if lt IE 9]>\n'])
    extend_([u'        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>\n'])
    extend_([u'        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>\n'])
    extend_([u'    <![endif]-->\n'])
    extend_([u'\n'])
    extend_([u'    <script src="/static/javascript/utils.js"></script>\n'])
    extend_([u'\n'])
    extend_([u'</head>\n'])
    extend_([u'\n'])
    extend_([u'<body>\n'])
    extend_([u'\n'])
    extend_([u'    <!-- Navigation -->\n'])
    extend_([u'    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">\n'])
    extend_([u'        <div class="container">\n'])
    extend_([u'            <!-- Brand and toggle get grouped for better mobile display -->\n'])
    extend_([u'            <div class="navbar-header">\n'])
    extend_([u'                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">\n'])
    extend_([u'                    <span class="sr-only">Alternar navega\xe7\xe3o</span>\n'])
    extend_([u'                    <span class="icon-bar"></span>\n'])
    extend_([u'                    <span class="icon-bar"></span>\n'])
    extend_([u'                    <span class="icon-bar"></span>\n'])
    extend_([u'                </button>\n'])
    extend_([u'                <a class="navbar-brand" href="#">Maxig\xeanios</a>\n'])
    extend_([u'            </div>\n'])
    extend_([u'            <!-- Collect the nav links, forms, and other content for toggling -->\n'])
    extend_([u'            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">\n'])
    extend_([u'                <ul class="nav navbar-nav navbar-right">\n'])
    extend_([u'                    <li>\n'])
    extend_([u'                        <a href="#" title="Sobre a empresa.">Sobre</a>\n'])
    extend_([u'                    </li>\n'])
    extend_([u'                    <li>\n'])
    extend_([u'                        <a href="#" title="Nossos Servi\xe7os.">Servi\xe7os</a>\n'])
    extend_([u'                    </li>\n'])
    extend_([u'                    <li>\n'])
    extend_([u'                        <a href="#" title="Clientes e Parceiros Satisfeitos.">Portif\xf3lio</a>\n'])
    extend_([u'                    </li>\n'])
    extend_([u'                    <li>\n'])
    extend_([u'                        <a href="#" title="Novidades da Maxig\xeanios.">Not\xedcias</a>\n'])
    extend_([u'                    </li>\n'])
    extend_([u'                    <li>\n'])
    extend_([u'                        <a href="#" title="Deixe o seu recado.">Contato</a>\n'])
    extend_([u'                    </li>\n'])
    extend_([u'                </ul>\n'])
    extend_([u'            </div>\n'])
    extend_([u'            <!-- /.navbar-collapse -->\n'])
    extend_([u'        </div>\n'])
    extend_([u'        <!-- /.container -->\n'])
    extend_([u'    </nav>\n'])
    extend_([u'\n'])
    extend_([u'    <!-- Header -->\n'])
    extend_([u'    <div class="intro-header">\n'])
    extend_([u'\n'])
    extend_([u'        <div class="container">\n'])
    extend_([u'\n'])
    extend_([u'            <div class="row">\n'])
    extend_([u'                <div class="col-lg-12">\n'])
    extend_([u'                    <div class="intro-message">\n'])
    extend_([u'                        <h1>Maxig\xeanios</h1>\n'])
    extend_([u'                        <h3>Genialidade em Solu\xe7\xf5es Tecnol\xf3gicas.</h3>\n'])
    extend_([u'                        <hr class="intro-divider">\n'])
    extend_([u'                        <ul class="list-inline intro-social-buttons">\n'])
    extend_([u'                            <li>\n'])
    extend_([u'                                <a href="#" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>\n'])
    extend_([u'                            </li>\n'])
    extend_([u'                            <li>\n'])
    extend_([u'                                <a href="#" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>\n'])
    extend_([u'                            </li>\n'])
    extend_([u'                            <li>\n'])
    extend_([u'                                <a href="#" class="btn btn-default btn-lg"><i class="fa fa-facebook fa-fw"></i> <span class="network-name">Facebook</span></a>\n'])
    extend_([u'                            </li>\n'])
    extend_([u'                        </ul>\n'])
    extend_([u'                    </div>\n'])
    extend_([u'                </div>\n'])
    extend_([u'            </div>\n'])
    extend_([u'\n'])
    extend_([u'        </div>\n'])
    extend_([u'        <!-- /.container -->\n'])
    extend_([u'\n'])
    extend_([u'    </div>\n'])
    extend_([u'    <!-- /.intro-header -->\n'])
    extend_([u'\n'])
    extend_([u'    <!-- Page Content -->\n'])
    extend_([u'\n'])
    extend_([u'    <div class="content-section-a">\n'])
    extend_([u'\n'])
    extend_([u'        <div class="container">\n'])
    extend_([u'\n'])
    extend_([u'            <div class="row">\n'])
    extend_([u'                <div class="col-lg-5 col-sm-6">\n'])
    extend_([u'                    <hr class="section-heading-spacer">\n'])
    extend_([u'                    <div class="clearfix"></div>\n'])
    extend_([u'                    <h2 class="section-heading">Aplica\xe7\xf5es Mobile:<br>IOS, Android e Windows Phone.</h2>\n'])
    extend_([u'                    <p class="lead">Desenvolvimento de Aplica\xe7\xf5es Mobile nas principais plataformas do mercado.</p>\n'])
    extend_([u'                </div>\n'])
    extend_([u'                <div class="col-lg-5 col-lg-offset-2 col-sm-6">\n'])
    extend_([u'                    <img class="img-responsive" src="/static/images/ipad.png" alt="">\n'])
    extend_([u'                </div>\n'])
    extend_([u'            </div>\n'])
    extend_([u'\n'])
    extend_([u'        </div>\n'])
    extend_([u'        <!-- /.container -->\n'])
    extend_([u'\n'])
    extend_([u'    </div>\n'])
    extend_([u'    <!-- /.content-section-a -->\n'])
    extend_([u'\n'])
    extend_([u'    <div class="content-section-b">\n'])
    extend_([u'\n'])
    extend_([u'        <div class="container">\n'])
    extend_([u'\n'])
    extend_([u'            <div class="row">\n'])
    extend_([u'                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">\n'])
    extend_([u'                    <hr class="section-heading-spacer">\n'])
    extend_([u'                    <div class="clearfix"></div>\n'])
    extend_([u'                    <h2 class="section-heading">Sistemas e Websites<br>Responsivos e personaliz\xe1veis.</h2>\n'])
    extend_([u'                    <p class="lead">Desenvolva conosco o seu sistema ou seu webiste responsivo, totalmente personaliz\xe1vel.</p>\n'])
    extend_([u'                </div>\n'])
    extend_([u'                <div class="col-lg-5 col-sm-pull-6  col-sm-6">\n'])
    extend_([u'                    <img class="img-responsive" src="/static/images/dog.png" alt="">\n'])
    extend_([u'                </div>\n'])
    extend_([u'            </div>\n'])
    extend_([u'\n'])
    extend_([u'        </div>\n'])
    extend_([u'        <!-- /.container -->\n'])
    extend_([u'\n'])
    extend_([u'    </div>\n'])
    extend_([u'    <!-- /.content-section-b -->\n'])
    extend_([u'\n'])
    extend_([u'    <div class="content-section-a">\n'])
    extend_([u'\n'])
    extend_([u'        <div class="container">\n'])
    extend_([u'\n'])
    extend_([u'            <div class="row">\n'])
    extend_([u'                <div class="col-lg-5 col-sm-6">\n'])
    extend_([u'                    <hr class="section-heading-spacer">\n'])
    extend_([u'                    <div class="clearfix"></div>\n'])
    extend_([u'                    <h2 class="section-heading">Apps Nativas ou Hibridas<br>IOS, Android ou Windows Phone</h2>\n'])
    extend_([u'                    <p class="lead">Desenvolvemos Apps nativas ou h\xedbridas nas pr\xedncipais plataformas do mercado.</p>\n'])
    extend_([u'                </div>\n'])
    extend_([u'                <div class="col-lg-5 col-lg-offset-2 col-sm-6">\n'])
    extend_([u'                    <img class="img-responsive" src="/static/images/phones.png" alt="">\n'])
    extend_([u'                </div>\n'])
    extend_([u'            </div>\n'])
    extend_([u'\n'])
    extend_([u'        </div>\n'])
    extend_([u'        <!-- /.container -->\n'])
    extend_([u'\n'])
    extend_([u'    </div>\n'])
    extend_([u'    <!-- /.content-section-a -->\n'])
    extend_([u'\n'])
    extend_([u'    <div class="banner">\n'])
    extend_([u'\n'])
    extend_([u'        <div class="container">\n'])
    extend_([u'\n'])
    extend_([u'            <div class="row">\n'])
    extend_([u'                <div class="col-lg-6">\n'])
    extend_([u'                    <h2>Conecte-se conosco:</h2>\n'])
    extend_([u'                </div>\n'])
    extend_([u'                <div class="col-lg-6">\n'])
    extend_([u'                    <ul class="list-inline banner-social-buttons">\n'])
    extend_([u'                        <li>\n'])
    extend_([u'                            <a href="#" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>\n'])
    extend_([u'                        </li>\n'])
    extend_([u'                        <li>\n'])
    extend_([u'                            <a href="#" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>\n'])
    extend_([u'                        </li>\n'])
    extend_([u'                        <li>\n'])
    extend_([u'                            <a href="#" class="btn btn-default btn-lg"><i class="fa fa-facebook fa-fw"></i> <span class="network-name">Facebook</span></a>\n'])
    extend_([u'                        </li>\n'])
    extend_([u'                    </ul>\n'])
    extend_([u'                </div>\n'])
    extend_([u'            </div>\n'])
    extend_([u'\n'])
    extend_([u'        </div>\n'])
    extend_([u'        <!-- /.container -->\n'])
    extend_([u'\n'])
    extend_([u'    </div>\n'])
    extend_([u'    <!-- /.banner -->\n'])
    extend_([u'\n'])
    extend_([u'    <!-- Footer -->\n'])
    extend_([u'    <footer>\n'])
    extend_([u'        <div class="container">\n'])
    extend_([u'            <div class="row">\n'])
    extend_([u'                <div class="col-lg-12">\n'])
    extend_([u'                    <ul class="list-inline">\n'])
    extend_([u'                        <li>\n'])
    extend_([u'                            <a href="#home">Home</a>\n'])
    extend_([u'                        </li>\n'])
    extend_([u'                        <li class="footer-menu-divider">&sdot;</li>\n'])
    extend_([u'                        <li>\n'])
    extend_([u'                            <a href="#about" title="Sobre a empresa.">Sobre</a>\n'])
    extend_([u'                        </li>\n'])
    extend_([u'                        <li class="footer-menu-divider">&sdot;</li>\n'])
    extend_([u'                        <li>\n'])
    extend_([u'                            <a href="#services">Servi\xe7os</a>\n'])
    extend_([u'                        </li>\n'])
    extend_([u'                        <li class="footer-menu-divider">&sdot;</li>\n'])
    extend_([u'                        <li>\n'])
    extend_([u'                            <a href="#services">Portif\xf3lio</a>\n'])
    extend_([u'                        </li>\n'])
    extend_([u'                        <li class="footer-menu-divider">&sdot;</li>\n'])
    extend_([u'                        <li>\n'])
    extend_([u'                            <a href="#services">Not\xedcias</a>\n'])
    extend_([u'                        </li>\n'])
    extend_([u'                        <li class="footer-menu-divider">&sdot;</li>\n'])
    extend_([u'                        <li>\n'])
    extend_([u'                            <a href="#contact">Contato</a>\n'])
    extend_([u'                        </li>\n'])
    extend_([u'                    </ul>\n'])
    extend_([u'                    <p class="copyright text-muted small">Copyright &copy; Maxig\xeanios <script type="text/javascript">document.write(get_actual_year());</script>. Todos direitos reservados. <br>Estamos \xe0 tua disposi\xe7\xe3o: (51) 9390.3511 | E-mail: comercial@maxigenios.com.br</p>\n'])
    extend_([u'                </div>\n'])
    extend_([u'            </div>\n'])
    extend_([u'        </div>\n'])
    extend_([u'    </footer>\n'])
    extend_([u'\n'])
    extend_([u'    <!-- jQuery -->\n'])
    extend_([u'    <script src="/static/javascript/jquery.js"></script>\n'])
    extend_([u'\n'])
    extend_([u'    <!-- Bootstrap Core JavaScript -->\n'])
    extend_([u'    <script src="/static/javascript/bootstrap.min.js"></script>\n'])
    extend_([u'\n'])
    extend_([u'    <!-- Chat -->\n'])
    extend_([u'\n'])
    extend_([u'    <!-- Start of Tawk.to Script -->\n'])
    extend_([u'    <script type="text/javascript">\n'])
    extend_([u'        var ', escape_(_Tawk_API, True), u'={},', escape_(_Tawk_LoadStart, True), u'=new Date();\n'])
    extend_([u'        (function(){\n'])
    extend_([u'            var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];\n'])
    extend_([u'            s1.async=true;\n'])
    extend_([u"            s1.src='https://embed.tawk.to/55082d28e1dea9e22660eeaa/default';\n"])
    extend_([u"            s1.charset='UTF-8';\n"])
    extend_([u"            s1.setAttribute('crossorigin','*');\n"])
    extend_([u'            s0.parentNode.insertBefore(s1,s0);\n'])
    extend_([u'            }\n'])
    extend_([u'        )();\n'])
    extend_([u'    </script>\n'])
    extend_([u'    <!--End of Tawk.to Script-->\n'])
    extend_([u'\n'])
    extend_([u'    <!-- Hotjar Tracking Code for www.maxigenios.com.br -->\n'])
    extend_([u'    <script>\n'])
    extend_([u'        (function(f,b){\n'])
    extend_([u'            var c;\n'])
    extend_([u'            f.hj=f.hj||function(){(f.hj.q=f.hj.q||[]).push(arguments)};\n'])
    extend_([u'            f._hjSettings={hjid:32981, hjsv:4};\n'])
    extend_([u'            c=b.createElement("script");c.async=1;\n'])
    extend_([u'            c.src="//static.hotjar.com/c/hotjar-"+f._hjSettings.hjid+".js?sv="+f._hjSettings.hjsv;\n'])
    extend_([u'            b.getElementsByTagName("head")[0].appendChild(c);\n'])
    extend_([u'        })(window,document);\n'])
    extend_([u'    </script>\n'])
    extend_([u'\n'])
    extend_([u'</body>\n'])
    extend_([u'\n'])
    extend_([u'</html>\n'])

    return self

layout = CompiledTemplate(layout, 'templates/site/layout.html')
join_ = layout._join; escape_ = layout._escape

